package com.zht.emqdemo.rds.mapper;

import com.zht.emqdemo.rds.model.UploadRecord;
import com.zht.emqdemo.rds.model.UploadRecordCriteria.Criteria;
import com.zht.emqdemo.rds.model.UploadRecordCriteria.Criterion;
import com.zht.emqdemo.rds.model.UploadRecordCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UploadRecordSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String countByExample(UploadRecordCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("upload_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String deleteByExample(UploadRecordCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("upload_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String insertSelective(UploadRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("upload_record");

        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerOne() != null) {
            sql.VALUES("power_one", "#{powerOne,jdbcType=INTEGER}");
        }
        
        if (record.getPowerTwo() != null) {
            sql.VALUES("power_two", "#{powerTwo,jdbcType=INTEGER}");
        }
        
        if (record.getPowerThree() != null) {
            sql.VALUES("power_three", "#{powerThree,jdbcType=INTEGER}");
        }
        
        if (record.getPowerFour() != null) {
            sql.VALUES("power_four", "#{powerFour,jdbcType=INTEGER}");
        }
        
        if (record.getTemperatureOne() != null) {
            sql.VALUES("temperature_one", "#{temperatureOne,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureTwo() != null) {
            sql.VALUES("temperature_two", "#{temperatureTwo,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureThree() != null) {
            sql.VALUES("temperature_three", "#{temperatureThree,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureFour() != null) {
            sql.VALUES("temperature_four", "#{temperatureFour,jdbcType=DECIMAL}");
        }
        
        if (record.getValueOne() != null) {
            sql.VALUES("value_one", "#{valueOne,jdbcType=INTEGER}");
        }
        
        if (record.getValueTwo() != null) {
            sql.VALUES("value_two", "#{valueTwo,jdbcType=INTEGER}");
        }
        
        if (record.getUploadDate() != null) {
            sql.VALUES("upload_date", "#{uploadDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCabinetId() != null) {
            sql.VALUES("cabinet_id", "#{cabinetId,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String selectByExample(UploadRecordCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("power_one");
        sql.SELECT("power_two");
        sql.SELECT("power_three");
        sql.SELECT("power_four");
        sql.SELECT("temperature_one");
        sql.SELECT("temperature_two");
        sql.SELECT("temperature_three");
        sql.SELECT("temperature_four");
        sql.SELECT("value_one");
        sql.SELECT("value_two");
        sql.SELECT("upload_date");
        sql.SELECT("cabinet_id");
        sql.FROM("upload_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UploadRecord record = (UploadRecord) parameter.get("record");
        UploadRecordCriteria example = (UploadRecordCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("upload_record");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getPowerOne() != null) {
            sql.SET("power_one = #{record.powerOne,jdbcType=INTEGER}");
        }
        
        if (record.getPowerTwo() != null) {
            sql.SET("power_two = #{record.powerTwo,jdbcType=INTEGER}");
        }
        
        if (record.getPowerThree() != null) {
            sql.SET("power_three = #{record.powerThree,jdbcType=INTEGER}");
        }
        
        if (record.getPowerFour() != null) {
            sql.SET("power_four = #{record.powerFour,jdbcType=INTEGER}");
        }
        
        if (record.getTemperatureOne() != null) {
            sql.SET("temperature_one = #{record.temperatureOne,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureTwo() != null) {
            sql.SET("temperature_two = #{record.temperatureTwo,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureThree() != null) {
            sql.SET("temperature_three = #{record.temperatureThree,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureFour() != null) {
            sql.SET("temperature_four = #{record.temperatureFour,jdbcType=DECIMAL}");
        }
        
        if (record.getValueOne() != null) {
            sql.SET("value_one = #{record.valueOne,jdbcType=INTEGER}");
        }
        
        if (record.getValueTwo() != null) {
            sql.SET("value_two = #{record.valueTwo,jdbcType=INTEGER}");
        }
        
        if (record.getUploadDate() != null) {
            sql.SET("upload_date = #{record.uploadDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCabinetId() != null) {
            sql.SET("cabinet_id = #{record.cabinetId,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("upload_record");
        
        sql.SET("id = #{record.id,jdbcType=VARCHAR}");
        sql.SET("power_one = #{record.powerOne,jdbcType=INTEGER}");
        sql.SET("power_two = #{record.powerTwo,jdbcType=INTEGER}");
        sql.SET("power_three = #{record.powerThree,jdbcType=INTEGER}");
        sql.SET("power_four = #{record.powerFour,jdbcType=INTEGER}");
        sql.SET("temperature_one = #{record.temperatureOne,jdbcType=DECIMAL}");
        sql.SET("temperature_two = #{record.temperatureTwo,jdbcType=DECIMAL}");
        sql.SET("temperature_three = #{record.temperatureThree,jdbcType=DECIMAL}");
        sql.SET("temperature_four = #{record.temperatureFour,jdbcType=DECIMAL}");
        sql.SET("value_one = #{record.valueOne,jdbcType=INTEGER}");
        sql.SET("value_two = #{record.valueTwo,jdbcType=INTEGER}");
        sql.SET("upload_date = #{record.uploadDate,jdbcType=TIMESTAMP}");
        sql.SET("cabinet_id = #{record.cabinetId,jdbcType=VARCHAR}");
        
        UploadRecordCriteria example = (UploadRecordCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(UploadRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("upload_record");
        
        if (record.getPowerOne() != null) {
            sql.SET("power_one = #{powerOne,jdbcType=INTEGER}");
        }
        
        if (record.getPowerTwo() != null) {
            sql.SET("power_two = #{powerTwo,jdbcType=INTEGER}");
        }
        
        if (record.getPowerThree() != null) {
            sql.SET("power_three = #{powerThree,jdbcType=INTEGER}");
        }
        
        if (record.getPowerFour() != null) {
            sql.SET("power_four = #{powerFour,jdbcType=INTEGER}");
        }
        
        if (record.getTemperatureOne() != null) {
            sql.SET("temperature_one = #{temperatureOne,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureTwo() != null) {
            sql.SET("temperature_two = #{temperatureTwo,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureThree() != null) {
            sql.SET("temperature_three = #{temperatureThree,jdbcType=DECIMAL}");
        }
        
        if (record.getTemperatureFour() != null) {
            sql.SET("temperature_four = #{temperatureFour,jdbcType=DECIMAL}");
        }
        
        if (record.getValueOne() != null) {
            sql.SET("value_one = #{valueOne,jdbcType=INTEGER}");
        }
        
        if (record.getValueTwo() != null) {
            sql.SET("value_two = #{valueTwo,jdbcType=INTEGER}");
        }
        
        if (record.getUploadDate() != null) {
            sql.SET("upload_date = #{uploadDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCabinetId() != null) {
            sql.SET("cabinet_id = #{cabinetId,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, UploadRecordCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}