package com.zht.emqdemo.rds.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CabinetInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public CabinetInfoCriteria() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPowerOneIsNull() {
            addCriterion("power_one is null");
            return (Criteria) this;
        }

        public Criteria andPowerOneIsNotNull() {
            addCriterion("power_one is not null");
            return (Criteria) this;
        }

        public Criteria andPowerOneEqualTo(Integer value) {
            addCriterion("power_one =", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotEqualTo(Integer value) {
            addCriterion("power_one <>", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneGreaterThan(Integer value) {
            addCriterion("power_one >", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_one >=", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneLessThan(Integer value) {
            addCriterion("power_one <", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneLessThanOrEqualTo(Integer value) {
            addCriterion("power_one <=", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneIn(List<Integer> values) {
            addCriterion("power_one in", values, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotIn(List<Integer> values) {
            addCriterion("power_one not in", values, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneBetween(Integer value1, Integer value2) {
            addCriterion("power_one between", value1, value2, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotBetween(Integer value1, Integer value2) {
            addCriterion("power_one not between", value1, value2, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIsNull() {
            addCriterion("power_two is null");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIsNotNull() {
            addCriterion("power_two is not null");
            return (Criteria) this;
        }

        public Criteria andPowerTwoEqualTo(Integer value) {
            addCriterion("power_two =", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotEqualTo(Integer value) {
            addCriterion("power_two <>", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoGreaterThan(Integer value) {
            addCriterion("power_two >", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_two >=", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoLessThan(Integer value) {
            addCriterion("power_two <", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoLessThanOrEqualTo(Integer value) {
            addCriterion("power_two <=", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIn(List<Integer> values) {
            addCriterion("power_two in", values, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotIn(List<Integer> values) {
            addCriterion("power_two not in", values, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoBetween(Integer value1, Integer value2) {
            addCriterion("power_two between", value1, value2, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("power_two not between", value1, value2, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIsNull() {
            addCriterion("power_three is null");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIsNotNull() {
            addCriterion("power_three is not null");
            return (Criteria) this;
        }

        public Criteria andPowerThreeEqualTo(Integer value) {
            addCriterion("power_three =", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotEqualTo(Integer value) {
            addCriterion("power_three <>", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeGreaterThan(Integer value) {
            addCriterion("power_three >", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_three >=", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeLessThan(Integer value) {
            addCriterion("power_three <", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeLessThanOrEqualTo(Integer value) {
            addCriterion("power_three <=", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIn(List<Integer> values) {
            addCriterion("power_three in", values, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotIn(List<Integer> values) {
            addCriterion("power_three not in", values, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeBetween(Integer value1, Integer value2) {
            addCriterion("power_three between", value1, value2, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotBetween(Integer value1, Integer value2) {
            addCriterion("power_three not between", value1, value2, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerFourIsNull() {
            addCriterion("power_four is null");
            return (Criteria) this;
        }

        public Criteria andPowerFourIsNotNull() {
            addCriterion("power_four is not null");
            return (Criteria) this;
        }

        public Criteria andPowerFourEqualTo(Integer value) {
            addCriterion("power_four =", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourNotEqualTo(Integer value) {
            addCriterion("power_four <>", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourGreaterThan(Integer value) {
            addCriterion("power_four >", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_four >=", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourLessThan(Integer value) {
            addCriterion("power_four <", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourLessThanOrEqualTo(Integer value) {
            addCriterion("power_four <=", value, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourIn(List<Integer> values) {
            addCriterion("power_four in", values, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourNotIn(List<Integer> values) {
            addCriterion("power_four not in", values, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourBetween(Integer value1, Integer value2) {
            addCriterion("power_four between", value1, value2, "powerFour");
            return (Criteria) this;
        }

        public Criteria andPowerFourNotBetween(Integer value1, Integer value2) {
            addCriterion("power_four not between", value1, value2, "powerFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIsNull() {
            addCriterion("temperature_one is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIsNotNull() {
            addCriterion("temperature_one is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneEqualTo(BigDecimal value) {
            addCriterion("temperature_one =", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotEqualTo(BigDecimal value) {
            addCriterion("temperature_one <>", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneGreaterThan(BigDecimal value) {
            addCriterion("temperature_one >", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_one >=", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneLessThan(BigDecimal value) {
            addCriterion("temperature_one <", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_one <=", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIn(List<BigDecimal> values) {
            addCriterion("temperature_one in", values, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotIn(List<BigDecimal> values) {
            addCriterion("temperature_one not in", values, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_one between", value1, value2, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_one not between", value1, value2, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIsNull() {
            addCriterion("temperature_two is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIsNotNull() {
            addCriterion("temperature_two is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoEqualTo(BigDecimal value) {
            addCriterion("temperature_two =", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotEqualTo(BigDecimal value) {
            addCriterion("temperature_two <>", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoGreaterThan(BigDecimal value) {
            addCriterion("temperature_two >", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_two >=", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoLessThan(BigDecimal value) {
            addCriterion("temperature_two <", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_two <=", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIn(List<BigDecimal> values) {
            addCriterion("temperature_two in", values, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotIn(List<BigDecimal> values) {
            addCriterion("temperature_two not in", values, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_two between", value1, value2, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_two not between", value1, value2, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIsNull() {
            addCriterion("temperature_three is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIsNotNull() {
            addCriterion("temperature_three is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeEqualTo(BigDecimal value) {
            addCriterion("temperature_three =", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotEqualTo(BigDecimal value) {
            addCriterion("temperature_three <>", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeGreaterThan(BigDecimal value) {
            addCriterion("temperature_three >", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_three >=", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeLessThan(BigDecimal value) {
            addCriterion("temperature_three <", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_three <=", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIn(List<BigDecimal> values) {
            addCriterion("temperature_three in", values, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotIn(List<BigDecimal> values) {
            addCriterion("temperature_three not in", values, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_three between", value1, value2, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_three not between", value1, value2, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourIsNull() {
            addCriterion("temperature_four is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourIsNotNull() {
            addCriterion("temperature_four is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourEqualTo(BigDecimal value) {
            addCriterion("temperature_four =", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourNotEqualTo(BigDecimal value) {
            addCriterion("temperature_four <>", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourGreaterThan(BigDecimal value) {
            addCriterion("temperature_four >", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_four >=", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourLessThan(BigDecimal value) {
            addCriterion("temperature_four <", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_four <=", value, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourIn(List<BigDecimal> values) {
            addCriterion("temperature_four in", values, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourNotIn(List<BigDecimal> values) {
            addCriterion("temperature_four not in", values, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_four between", value1, value2, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andTemperatureFourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_four not between", value1, value2, "temperatureFour");
            return (Criteria) this;
        }

        public Criteria andValueOneIsNull() {
            addCriterion("value_one is null");
            return (Criteria) this;
        }

        public Criteria andValueOneIsNotNull() {
            addCriterion("value_one is not null");
            return (Criteria) this;
        }

        public Criteria andValueOneEqualTo(Integer value) {
            addCriterion("value_one =", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotEqualTo(Integer value) {
            addCriterion("value_one <>", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneGreaterThan(Integer value) {
            addCriterion("value_one >", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("value_one >=", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneLessThan(Integer value) {
            addCriterion("value_one <", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneLessThanOrEqualTo(Integer value) {
            addCriterion("value_one <=", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneIn(List<Integer> values) {
            addCriterion("value_one in", values, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotIn(List<Integer> values) {
            addCriterion("value_one not in", values, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneBetween(Integer value1, Integer value2) {
            addCriterion("value_one between", value1, value2, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotBetween(Integer value1, Integer value2) {
            addCriterion("value_one not between", value1, value2, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueTwoIsNull() {
            addCriterion("value_two is null");
            return (Criteria) this;
        }

        public Criteria andValueTwoIsNotNull() {
            addCriterion("value_two is not null");
            return (Criteria) this;
        }

        public Criteria andValueTwoEqualTo(Integer value) {
            addCriterion("value_two =", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotEqualTo(Integer value) {
            addCriterion("value_two <>", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoGreaterThan(Integer value) {
            addCriterion("value_two >", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("value_two >=", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoLessThan(Integer value) {
            addCriterion("value_two <", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoLessThanOrEqualTo(Integer value) {
            addCriterion("value_two <=", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoIn(List<Integer> values) {
            addCriterion("value_two in", values, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotIn(List<Integer> values) {
            addCriterion("value_two not in", values, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoBetween(Integer value1, Integer value2) {
            addCriterion("value_two between", value1, value2, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("value_two not between", value1, value2, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("tenant_id like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("tenant_id not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneIsNull() {
            addCriterion("alarm_value_one is null");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneIsNotNull() {
            addCriterion("alarm_value_one is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneEqualTo(Integer value) {
            addCriterion("alarm_value_one =", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneNotEqualTo(Integer value) {
            addCriterion("alarm_value_one <>", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneGreaterThan(Integer value) {
            addCriterion("alarm_value_one >", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_value_one >=", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneLessThan(Integer value) {
            addCriterion("alarm_value_one <", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_value_one <=", value, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneIn(List<Integer> values) {
            addCriterion("alarm_value_one in", values, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneNotIn(List<Integer> values) {
            addCriterion("alarm_value_one not in", values, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneBetween(Integer value1, Integer value2) {
            addCriterion("alarm_value_one between", value1, value2, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueOneNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_value_one not between", value1, value2, "alarmValueOne");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoIsNull() {
            addCriterion("alarm_value_two is null");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoIsNotNull() {
            addCriterion("alarm_value_two is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoEqualTo(Integer value) {
            addCriterion("alarm_value_two =", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoNotEqualTo(Integer value) {
            addCriterion("alarm_value_two <>", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoGreaterThan(Integer value) {
            addCriterion("alarm_value_two >", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("alarm_value_two >=", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoLessThan(Integer value) {
            addCriterion("alarm_value_two <", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoLessThanOrEqualTo(Integer value) {
            addCriterion("alarm_value_two <=", value, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoIn(List<Integer> values) {
            addCriterion("alarm_value_two in", values, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoNotIn(List<Integer> values) {
            addCriterion("alarm_value_two not in", values, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoBetween(Integer value1, Integer value2) {
            addCriterion("alarm_value_two between", value1, value2, "alarmValueTwo");
            return (Criteria) this;
        }

        public Criteria andAlarmValueTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("alarm_value_two not between", value1, value2, "alarmValueTwo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cabinet_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}