package com.zht.emqdemo.rds.model;

import java.math.BigDecimal;

public class CabinetInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.power_one
     *
     * @mbg.generated
     */
    private Integer powerOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.power_two
     *
     * @mbg.generated
     */
    private Integer powerTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.power_three
     *
     * @mbg.generated
     */
    private Integer powerThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.power_four
     *
     * @mbg.generated
     */
    private Integer powerFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.temperature_one
     *
     * @mbg.generated
     */
    private BigDecimal temperatureOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.temperature_two
     *
     * @mbg.generated
     */
    private BigDecimal temperatureTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.temperature_three
     *
     * @mbg.generated
     */
    private BigDecimal temperatureThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.temperature_four
     *
     * @mbg.generated
     */
    private BigDecimal temperatureFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.value_one
     *
     * @mbg.generated
     */
    private Integer valueOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.value_two
     *
     * @mbg.generated
     */
    private Integer valueTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.alarm_value_one
     *
     * @mbg.generated
     */
    private Integer alarmValueOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cabinet_info.alarm_value_two
     *
     * @mbg.generated
     */
    private Integer alarmValueTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.id
     *
     * @return the value of cabinet_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.id
     *
     * @param id the value for cabinet_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.status
     *
     * @return the value of cabinet_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.status
     *
     * @param status the value for cabinet_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.power_one
     *
     * @return the value of cabinet_info.power_one
     *
     * @mbg.generated
     */
    public Integer getPowerOne() {
        return powerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.power_one
     *
     * @param powerOne the value for cabinet_info.power_one
     *
     * @mbg.generated
     */
    public void setPowerOne(Integer powerOne) {
        this.powerOne = powerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.power_two
     *
     * @return the value of cabinet_info.power_two
     *
     * @mbg.generated
     */
    public Integer getPowerTwo() {
        return powerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.power_two
     *
     * @param powerTwo the value for cabinet_info.power_two
     *
     * @mbg.generated
     */
    public void setPowerTwo(Integer powerTwo) {
        this.powerTwo = powerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.power_three
     *
     * @return the value of cabinet_info.power_three
     *
     * @mbg.generated
     */
    public Integer getPowerThree() {
        return powerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.power_three
     *
     * @param powerThree the value for cabinet_info.power_three
     *
     * @mbg.generated
     */
    public void setPowerThree(Integer powerThree) {
        this.powerThree = powerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.power_four
     *
     * @return the value of cabinet_info.power_four
     *
     * @mbg.generated
     */
    public Integer getPowerFour() {
        return powerFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.power_four
     *
     * @param powerFour the value for cabinet_info.power_four
     *
     * @mbg.generated
     */
    public void setPowerFour(Integer powerFour) {
        this.powerFour = powerFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.temperature_one
     *
     * @return the value of cabinet_info.temperature_one
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureOne() {
        return temperatureOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.temperature_one
     *
     * @param temperatureOne the value for cabinet_info.temperature_one
     *
     * @mbg.generated
     */
    public void setTemperatureOne(BigDecimal temperatureOne) {
        this.temperatureOne = temperatureOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.temperature_two
     *
     * @return the value of cabinet_info.temperature_two
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureTwo() {
        return temperatureTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.temperature_two
     *
     * @param temperatureTwo the value for cabinet_info.temperature_two
     *
     * @mbg.generated
     */
    public void setTemperatureTwo(BigDecimal temperatureTwo) {
        this.temperatureTwo = temperatureTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.temperature_three
     *
     * @return the value of cabinet_info.temperature_three
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureThree() {
        return temperatureThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.temperature_three
     *
     * @param temperatureThree the value for cabinet_info.temperature_three
     *
     * @mbg.generated
     */
    public void setTemperatureThree(BigDecimal temperatureThree) {
        this.temperatureThree = temperatureThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.temperature_four
     *
     * @return the value of cabinet_info.temperature_four
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureFour() {
        return temperatureFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.temperature_four
     *
     * @param temperatureFour the value for cabinet_info.temperature_four
     *
     * @mbg.generated
     */
    public void setTemperatureFour(BigDecimal temperatureFour) {
        this.temperatureFour = temperatureFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.value_one
     *
     * @return the value of cabinet_info.value_one
     *
     * @mbg.generated
     */
    public Integer getValueOne() {
        return valueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.value_one
     *
     * @param valueOne the value for cabinet_info.value_one
     *
     * @mbg.generated
     */
    public void setValueOne(Integer valueOne) {
        this.valueOne = valueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.value_two
     *
     * @return the value of cabinet_info.value_two
     *
     * @mbg.generated
     */
    public Integer getValueTwo() {
        return valueTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.value_two
     *
     * @param valueTwo the value for cabinet_info.value_two
     *
     * @mbg.generated
     */
    public void setValueTwo(Integer valueTwo) {
        this.valueTwo = valueTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.tenant_id
     *
     * @return the value of cabinet_info.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.tenant_id
     *
     * @param tenantId the value for cabinet_info.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.alarm_value_one
     *
     * @return the value of cabinet_info.alarm_value_one
     *
     * @mbg.generated
     */
    public Integer getAlarmValueOne() {
        return alarmValueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.alarm_value_one
     *
     * @param alarmValueOne the value for cabinet_info.alarm_value_one
     *
     * @mbg.generated
     */
    public void setAlarmValueOne(Integer alarmValueOne) {
        this.alarmValueOne = alarmValueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cabinet_info.alarm_value_two
     *
     * @return the value of cabinet_info.alarm_value_two
     *
     * @mbg.generated
     */
    public Integer getAlarmValueTwo() {
        return alarmValueTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cabinet_info.alarm_value_two
     *
     * @param alarmValueTwo the value for cabinet_info.alarm_value_two
     *
     * @mbg.generated
     */
    public void setAlarmValueTwo(Integer alarmValueTwo) {
        this.alarmValueTwo = alarmValueTwo;
    }
}