package com.zht.emqdemo.rds.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class UploadRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.power_one
     *
     * @mbg.generated
     */
    private Integer powerOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.power_two
     *
     * @mbg.generated
     */
    private Integer powerTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.power_three
     *
     * @mbg.generated
     */
    private Integer powerThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.temperature_one
     *
     * @mbg.generated
     */
    private BigDecimal temperatureOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.temperature_two
     *
     * @mbg.generated
     */
    private BigDecimal temperatureTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.temperature_three
     *
     * @mbg.generated
     */
    private BigDecimal temperatureThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.value_one
     *
     * @mbg.generated
     */
    private Integer valueOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.value_two
     *
     * @mbg.generated
     */
    private Integer valueTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.value_three
     *
     * @mbg.generated
     */
    private BigDecimal valueThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.value_four
     *
     * @mbg.generated
     */
    private BigDecimal valueFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.upload_date
     *
     * @mbg.generated
     */
    private LocalDateTime uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_record.cabinet_id
     *
     * @mbg.generated
     */
    private String cabinetId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.id
     *
     * @return the value of upload_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.id
     *
     * @param id the value for upload_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.power_one
     *
     * @return the value of upload_record.power_one
     *
     * @mbg.generated
     */
    public Integer getPowerOne() {
        return powerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.power_one
     *
     * @param powerOne the value for upload_record.power_one
     *
     * @mbg.generated
     */
    public void setPowerOne(Integer powerOne) {
        this.powerOne = powerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.power_two
     *
     * @return the value of upload_record.power_two
     *
     * @mbg.generated
     */
    public Integer getPowerTwo() {
        return powerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.power_two
     *
     * @param powerTwo the value for upload_record.power_two
     *
     * @mbg.generated
     */
    public void setPowerTwo(Integer powerTwo) {
        this.powerTwo = powerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.power_three
     *
     * @return the value of upload_record.power_three
     *
     * @mbg.generated
     */
    public Integer getPowerThree() {
        return powerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.power_three
     *
     * @param powerThree the value for upload_record.power_three
     *
     * @mbg.generated
     */
    public void setPowerThree(Integer powerThree) {
        this.powerThree = powerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.temperature_one
     *
     * @return the value of upload_record.temperature_one
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureOne() {
        return temperatureOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.temperature_one
     *
     * @param temperatureOne the value for upload_record.temperature_one
     *
     * @mbg.generated
     */
    public void setTemperatureOne(BigDecimal temperatureOne) {
        this.temperatureOne = temperatureOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.temperature_two
     *
     * @return the value of upload_record.temperature_two
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureTwo() {
        return temperatureTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.temperature_two
     *
     * @param temperatureTwo the value for upload_record.temperature_two
     *
     * @mbg.generated
     */
    public void setTemperatureTwo(BigDecimal temperatureTwo) {
        this.temperatureTwo = temperatureTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.temperature_three
     *
     * @return the value of upload_record.temperature_three
     *
     * @mbg.generated
     */
    public BigDecimal getTemperatureThree() {
        return temperatureThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.temperature_three
     *
     * @param temperatureThree the value for upload_record.temperature_three
     *
     * @mbg.generated
     */
    public void setTemperatureThree(BigDecimal temperatureThree) {
        this.temperatureThree = temperatureThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.value_one
     *
     * @return the value of upload_record.value_one
     *
     * @mbg.generated
     */
    public Integer getValueOne() {
        return valueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.value_one
     *
     * @param valueOne the value for upload_record.value_one
     *
     * @mbg.generated
     */
    public void setValueOne(Integer valueOne) {
        this.valueOne = valueOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.value_two
     *
     * @return the value of upload_record.value_two
     *
     * @mbg.generated
     */
    public Integer getValueTwo() {
        return valueTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.value_two
     *
     * @param valueTwo the value for upload_record.value_two
     *
     * @mbg.generated
     */
    public void setValueTwo(Integer valueTwo) {
        this.valueTwo = valueTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.value_three
     *
     * @return the value of upload_record.value_three
     *
     * @mbg.generated
     */
    public BigDecimal getValueThree() {
        return valueThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.value_three
     *
     * @param valueThree the value for upload_record.value_three
     *
     * @mbg.generated
     */
    public void setValueThree(BigDecimal valueThree) {
        this.valueThree = valueThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.value_four
     *
     * @return the value of upload_record.value_four
     *
     * @mbg.generated
     */
    public BigDecimal getValueFour() {
        return valueFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.value_four
     *
     * @param valueFour the value for upload_record.value_four
     *
     * @mbg.generated
     */
    public void setValueFour(BigDecimal valueFour) {
        this.valueFour = valueFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.upload_date
     *
     * @return the value of upload_record.upload_date
     *
     * @mbg.generated
     */
    public LocalDateTime getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.upload_date
     *
     * @param uploadDate the value for upload_record.upload_date
     *
     * @mbg.generated
     */
    public void setUploadDate(LocalDateTime uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_record.cabinet_id
     *
     * @return the value of upload_record.cabinet_id
     *
     * @mbg.generated
     */
    public String getCabinetId() {
        return cabinetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_record.cabinet_id
     *
     * @param cabinetId the value for upload_record.cabinet_id
     *
     * @mbg.generated
     */
    public void setCabinetId(String cabinetId) {
        this.cabinetId = cabinetId == null ? null : cabinetId.trim();
    }
}