package com.zht.emqdemo.rds.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class UploadRecordCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public UploadRecordCriteria() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPowerOneIsNull() {
            addCriterion("power_one is null");
            return (Criteria) this;
        }

        public Criteria andPowerOneIsNotNull() {
            addCriterion("power_one is not null");
            return (Criteria) this;
        }

        public Criteria andPowerOneEqualTo(Integer value) {
            addCriterion("power_one =", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotEqualTo(Integer value) {
            addCriterion("power_one <>", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneGreaterThan(Integer value) {
            addCriterion("power_one >", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_one >=", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneLessThan(Integer value) {
            addCriterion("power_one <", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneLessThanOrEqualTo(Integer value) {
            addCriterion("power_one <=", value, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneIn(List<Integer> values) {
            addCriterion("power_one in", values, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotIn(List<Integer> values) {
            addCriterion("power_one not in", values, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneBetween(Integer value1, Integer value2) {
            addCriterion("power_one between", value1, value2, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerOneNotBetween(Integer value1, Integer value2) {
            addCriterion("power_one not between", value1, value2, "powerOne");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIsNull() {
            addCriterion("power_two is null");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIsNotNull() {
            addCriterion("power_two is not null");
            return (Criteria) this;
        }

        public Criteria andPowerTwoEqualTo(Integer value) {
            addCriterion("power_two =", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotEqualTo(Integer value) {
            addCriterion("power_two <>", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoGreaterThan(Integer value) {
            addCriterion("power_two >", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_two >=", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoLessThan(Integer value) {
            addCriterion("power_two <", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoLessThanOrEqualTo(Integer value) {
            addCriterion("power_two <=", value, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoIn(List<Integer> values) {
            addCriterion("power_two in", values, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotIn(List<Integer> values) {
            addCriterion("power_two not in", values, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoBetween(Integer value1, Integer value2) {
            addCriterion("power_two between", value1, value2, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("power_two not between", value1, value2, "powerTwo");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIsNull() {
            addCriterion("power_three is null");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIsNotNull() {
            addCriterion("power_three is not null");
            return (Criteria) this;
        }

        public Criteria andPowerThreeEqualTo(Integer value) {
            addCriterion("power_three =", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotEqualTo(Integer value) {
            addCriterion("power_three <>", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeGreaterThan(Integer value) {
            addCriterion("power_three >", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeGreaterThanOrEqualTo(Integer value) {
            addCriterion("power_three >=", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeLessThan(Integer value) {
            addCriterion("power_three <", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeLessThanOrEqualTo(Integer value) {
            addCriterion("power_three <=", value, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeIn(List<Integer> values) {
            addCriterion("power_three in", values, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotIn(List<Integer> values) {
            addCriterion("power_three not in", values, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeBetween(Integer value1, Integer value2) {
            addCriterion("power_three between", value1, value2, "powerThree");
            return (Criteria) this;
        }

        public Criteria andPowerThreeNotBetween(Integer value1, Integer value2) {
            addCriterion("power_three not between", value1, value2, "powerThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIsNull() {
            addCriterion("temperature_one is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIsNotNull() {
            addCriterion("temperature_one is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneEqualTo(BigDecimal value) {
            addCriterion("temperature_one =", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotEqualTo(BigDecimal value) {
            addCriterion("temperature_one <>", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneGreaterThan(BigDecimal value) {
            addCriterion("temperature_one >", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_one >=", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneLessThan(BigDecimal value) {
            addCriterion("temperature_one <", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_one <=", value, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneIn(List<BigDecimal> values) {
            addCriterion("temperature_one in", values, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotIn(List<BigDecimal> values) {
            addCriterion("temperature_one not in", values, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_one between", value1, value2, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureOneNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_one not between", value1, value2, "temperatureOne");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIsNull() {
            addCriterion("temperature_two is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIsNotNull() {
            addCriterion("temperature_two is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoEqualTo(BigDecimal value) {
            addCriterion("temperature_two =", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotEqualTo(BigDecimal value) {
            addCriterion("temperature_two <>", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoGreaterThan(BigDecimal value) {
            addCriterion("temperature_two >", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_two >=", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoLessThan(BigDecimal value) {
            addCriterion("temperature_two <", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_two <=", value, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoIn(List<BigDecimal> values) {
            addCriterion("temperature_two in", values, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotIn(List<BigDecimal> values) {
            addCriterion("temperature_two not in", values, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_two between", value1, value2, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureTwoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_two not between", value1, value2, "temperatureTwo");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIsNull() {
            addCriterion("temperature_three is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIsNotNull() {
            addCriterion("temperature_three is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeEqualTo(BigDecimal value) {
            addCriterion("temperature_three =", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotEqualTo(BigDecimal value) {
            addCriterion("temperature_three <>", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeGreaterThan(BigDecimal value) {
            addCriterion("temperature_three >", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_three >=", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeLessThan(BigDecimal value) {
            addCriterion("temperature_three <", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("temperature_three <=", value, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeIn(List<BigDecimal> values) {
            addCriterion("temperature_three in", values, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotIn(List<BigDecimal> values) {
            addCriterion("temperature_three not in", values, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_three between", value1, value2, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andTemperatureThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("temperature_three not between", value1, value2, "temperatureThree");
            return (Criteria) this;
        }

        public Criteria andValueOneIsNull() {
            addCriterion("value_one is null");
            return (Criteria) this;
        }

        public Criteria andValueOneIsNotNull() {
            addCriterion("value_one is not null");
            return (Criteria) this;
        }

        public Criteria andValueOneEqualTo(Integer value) {
            addCriterion("value_one =", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotEqualTo(Integer value) {
            addCriterion("value_one <>", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneGreaterThan(Integer value) {
            addCriterion("value_one >", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneGreaterThanOrEqualTo(Integer value) {
            addCriterion("value_one >=", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneLessThan(Integer value) {
            addCriterion("value_one <", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneLessThanOrEqualTo(Integer value) {
            addCriterion("value_one <=", value, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneIn(List<Integer> values) {
            addCriterion("value_one in", values, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotIn(List<Integer> values) {
            addCriterion("value_one not in", values, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneBetween(Integer value1, Integer value2) {
            addCriterion("value_one between", value1, value2, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueOneNotBetween(Integer value1, Integer value2) {
            addCriterion("value_one not between", value1, value2, "valueOne");
            return (Criteria) this;
        }

        public Criteria andValueTwoIsNull() {
            addCriterion("value_two is null");
            return (Criteria) this;
        }

        public Criteria andValueTwoIsNotNull() {
            addCriterion("value_two is not null");
            return (Criteria) this;
        }

        public Criteria andValueTwoEqualTo(Integer value) {
            addCriterion("value_two =", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotEqualTo(Integer value) {
            addCriterion("value_two <>", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoGreaterThan(Integer value) {
            addCriterion("value_two >", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoGreaterThanOrEqualTo(Integer value) {
            addCriterion("value_two >=", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoLessThan(Integer value) {
            addCriterion("value_two <", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoLessThanOrEqualTo(Integer value) {
            addCriterion("value_two <=", value, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoIn(List<Integer> values) {
            addCriterion("value_two in", values, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotIn(List<Integer> values) {
            addCriterion("value_two not in", values, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoBetween(Integer value1, Integer value2) {
            addCriterion("value_two between", value1, value2, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueTwoNotBetween(Integer value1, Integer value2) {
            addCriterion("value_two not between", value1, value2, "valueTwo");
            return (Criteria) this;
        }

        public Criteria andValueThreeIsNull() {
            addCriterion("value_three is null");
            return (Criteria) this;
        }

        public Criteria andValueThreeIsNotNull() {
            addCriterion("value_three is not null");
            return (Criteria) this;
        }

        public Criteria andValueThreeEqualTo(BigDecimal value) {
            addCriterion("value_three =", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeNotEqualTo(BigDecimal value) {
            addCriterion("value_three <>", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeGreaterThan(BigDecimal value) {
            addCriterion("value_three >", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("value_three >=", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeLessThan(BigDecimal value) {
            addCriterion("value_three <", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("value_three <=", value, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeIn(List<BigDecimal> values) {
            addCriterion("value_three in", values, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeNotIn(List<BigDecimal> values) {
            addCriterion("value_three not in", values, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("value_three between", value1, value2, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueThreeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("value_three not between", value1, value2, "valueThree");
            return (Criteria) this;
        }

        public Criteria andValueFourIsNull() {
            addCriterion("value_four is null");
            return (Criteria) this;
        }

        public Criteria andValueFourIsNotNull() {
            addCriterion("value_four is not null");
            return (Criteria) this;
        }

        public Criteria andValueFourEqualTo(BigDecimal value) {
            addCriterion("value_four =", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourNotEqualTo(BigDecimal value) {
            addCriterion("value_four <>", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourGreaterThan(BigDecimal value) {
            addCriterion("value_four >", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("value_four >=", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourLessThan(BigDecimal value) {
            addCriterion("value_four <", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("value_four <=", value, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourIn(List<BigDecimal> values) {
            addCriterion("value_four in", values, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourNotIn(List<BigDecimal> values) {
            addCriterion("value_four not in", values, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("value_four between", value1, value2, "valueFour");
            return (Criteria) this;
        }

        public Criteria andValueFourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("value_four not between", value1, value2, "valueFour");
            return (Criteria) this;
        }

        public Criteria andUploadDateIsNull() {
            addCriterion("upload_date is null");
            return (Criteria) this;
        }

        public Criteria andUploadDateIsNotNull() {
            addCriterion("upload_date is not null");
            return (Criteria) this;
        }

        public Criteria andUploadDateEqualTo(LocalDateTime value) {
            addCriterion("upload_date =", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateNotEqualTo(LocalDateTime value) {
            addCriterion("upload_date <>", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateGreaterThan(LocalDateTime value) {
            addCriterion("upload_date >", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("upload_date >=", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateLessThan(LocalDateTime value) {
            addCriterion("upload_date <", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("upload_date <=", value, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateIn(List<LocalDateTime> values) {
            addCriterion("upload_date in", values, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateNotIn(List<LocalDateTime> values) {
            addCriterion("upload_date not in", values, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("upload_date between", value1, value2, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andUploadDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("upload_date not between", value1, value2, "uploadDate");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNull() {
            addCriterion("cabinet_id is null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIsNotNull() {
            addCriterion("cabinet_id is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetIdEqualTo(String value) {
            addCriterion("cabinet_id =", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotEqualTo(String value) {
            addCriterion("cabinet_id <>", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThan(String value) {
            addCriterion("cabinet_id >", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdGreaterThanOrEqualTo(String value) {
            addCriterion("cabinet_id >=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThan(String value) {
            addCriterion("cabinet_id <", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLessThanOrEqualTo(String value) {
            addCriterion("cabinet_id <=", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdLike(String value) {
            addCriterion("cabinet_id like", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotLike(String value) {
            addCriterion("cabinet_id not like", value, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdIn(List<String> values) {
            addCriterion("cabinet_id in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotIn(List<String> values) {
            addCriterion("cabinet_id not in", values, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdBetween(String value1, String value2) {
            addCriterion("cabinet_id between", value1, value2, "cabinetId");
            return (Criteria) this;
        }

        public Criteria andCabinetIdNotBetween(String value1, String value2) {
            addCriterion("cabinet_id not between", value1, value2, "cabinetId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upload_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table upload_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}